# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: 
          export mySqlHostname=capstone-customer-manager.mysql.database.azure.com
          export mySqlPass=Password1
          export mySqlSchema=capstone
          export mySqlUser=csr_root
          npm install
          npm run test2
        working-directory: ./BackEnd-Deploy/
